Added the possibility to config android-packageName and iosBundleIdentifier
SamVerschueren/cordova-config pull request #17
Opened 2016-06-14 05:55 UTC by rstraub

2016-06-14 06:25 UTC, SamVerschueren commented on package.json
> +  "version": "0.6.3",
Don't bump the version. I'll do it when releasing it.

2016-06-14 06:26 UTC, SamVerschueren commented on index.js
> +      if (!regex.test(packageName)) {
Add an empty line above the `if` statement

2016-06-14 06:28 UTC, SamVerschueren commented
Thank you very much for this PR! Some extra notes.

1. Indentation is wrong. Indent with tabs instead of spaces. I'd suggest to install an [EditorConfig](http://editorconfig.org/) plugins for your editor of choice.
2. Can you add some extra tests to test these 2 methods?

2016-06-14 07:03 UTC, rstraub commented
I made the changes you requested. Although when I actually ran the tests with the npm test script, none of them (even the ones that were defined earlier) seemed to work. I decided to put the tests in the same format as you did, as I am not familiar with the particular tooling setup I wasn't able to find a fix for it.

2016-06-14 08:12 UTC, SamVerschueren commented
@rstraub the [linter](https://github.com/sindresorhus/xo) is failing. Have to fix that first before I am able to merge and do a new release. If you have some time and are willing to do another PR for that, be my guest :). I can always help you understand the failures. If not, no problem, I'll have to see when I find some time to fix it.

2016-06-14 08:15 UTC, rstraub commented
Sounds like a plan. If I have some spare time I will check into it. 👍

2016-06-14 08:18 UTC, SamVerschueren commented
Alright, thanks 👍

2017-02-22 17:00 UTC, SamVerschueren requested changes
Files are wrongly named. Can you also rebase on master? It should hopefully solve the issues.

2017-02-22 17:00 UTC, SamVerschueren commented on test/setAndroidPackageName.js
> +import test from 'ava';
Rename the file to `set-android-package-name.js`

2017-02-22 17:00 UTC, SamVerschueren commented on test/setIOSBundleIdentifier.js
> +import test from 'ava';
Rename the file to `set-ios-bundle-identifier.js`

2017-03-08 06:41 UTC, SamVerschueren commented
Ping @rstraub Still interested in completing this?

2017-04-07 19:34 UTC, merged