Add method to set plugin variables
SamVerschueren/cordova-config pull request #22
Opened 2018-02-08 14:11 UTC by nihenaoar

An extra method is added to the API that allows to set a variable for a specified plugin in `config.xml` file.

2018-02-09 06:40 UTC, SamVerschueren requested changes
Thanks for the PR! Added some comments. Would it also be possible to remove the `package-lock.json` file?

2018-02-09 06:40 UTC, SamVerschueren commented on .jshintrc
> +{ "esversion":6 }
I'm not using jshint, so remove this file.

2018-02-09 06:40 UTC, SamVerschueren commented on index.js
> +			var doc = new et.ElementTree(et.XML(contents)); // eslint-disable-line babel/new-cap
Undo change

2018-02-09 06:40 UTC, SamVerschueren commented on index.js
> -'use strict';
Do not remove

2018-02-09 06:40 UTC, SamVerschueren commented on index.js
> +		var xml = et.XML(raw); // eslint-disable-line babel/new-cap
Undo

2018-02-09 06:40 UTC, SamVerschueren commented on index.js
> +		return pify(fs.writeFile, Promise)(this._file, this._doc.write({
Undo

2018-02-09 06:40 UTC, SamVerschueren commented on index.js
> +		fs.writeFileSync(this._file, this._doc.write({
Undo

2018-02-09 06:40 UTC, SamVerschueren commented on test/set-plugin-variable-value.js
> +import test from 'ava';
Can you add an extra test which sets multiple plugin variables?

2018-02-09 06:40 UTC, SamVerschueren commented on README.md
> +### #setPluginVariable(pluginName, variableName, variableValue)
I believe it would make more sense to use `addPluginVariable` instead. Because it's possible to call it multiple times.

2018-05-16 14:28 UTC, morellan commented
Any news on this @nihenaoar ?, I'd love to have this feature merged on the main repo

2018-05-20 04:43 UTC, nihenaoar commented
@morellan I've updated the PR, it's been moved to #23 since this one comes from a fork that's not mine.

2018-05-20 04:43 UTC, closed without merging